### PR TITLE
Add travis-ci config

### PR DESCRIPTION
**Pull request by rsolomakhin**

### CODE REVIEW

**Comment by rsolomakhin** [comment]
@roubert ptal

**Comment by roubert** [comment]
@ssundarraj owns this nowadays, and would be the suitable code reviewer.

**Comment by ssundarraj** [comment]
Can you also add the Android and Java tests to this?

**Comment by rsolomakhin** [comment]
@ssundarraj I'm afraid Travis CI support is not good enough to support both Android/Java and Linux/C++ build in the same repository. Please choose one. I prefer C++. :-)

(The pull request is currently not ready to submit, because I've been trying to make Travis CI work properly, so far without success.)

**Comment by ssundarraj** [comment]
That's unfortunate. I guess C++ is fine.

**Comment by rsolomakhin** [comment]
@ssundarraj Please take a look.

**Pull request merged**
