### PR TITLE
Remove deprecated C++ <functional>

### PR DESCRIPTION
**Pull request by tzik**
Some of function utilities defined in <functional> are deprecated in
C++11, and removed in C++17. Such as std::bind2nd, std::not1, and
std::binary_function.

This CL replaces them with lambda, so that the code can compile as
a C++17.

### CODE REVIEW

**Comment by tzik** [comment]
@sebsg, is there any chance of taking a look to this?

**Comment by sebsg** [comment]
Hey! Thank you for writing that patch. I just updated the repo since it had been a while and there were a couple of changes that should affect/help you.

Can you let me know if this helps? Thanks!

**Comment by sebsg** [comment]
Hi tzik, 

unfortunately we don't currently have plans to support C++17 in the short term unfortunately.

Therefore, even by applying this patch, I would not be able to promise that then next change we don't won't break on C++17.

Sorry for the incovenience.

cheers!

**Comment by tzik** [comment]
Just the community support works fine for us rather than the official support: We may send a pull request when we find a C++17 mode breakage, but you don't need to care about C++17 mode breakages.

As described in [a tracking downstream issue](https://bugs.chromium.org/p/chromium/issues/detail?id=752720#c26), libaddressinput is the last C++17 incompatible component for Chromium. Though it's possible to stick to C++14 for individual components, full C++17 adoption makes things easier for us.

Could you take this if this does not conflict to the goal of the project?

**Comment by tzik** [comment]
As we chatted, let me move the change to the internal repo.

**Pull request closed without merging**
