### PR TITLE
(AUTOMATIC) opensource update

### PR DESCRIPTION
**Pull request by tanderson-google**

### CODE REVIEW

**Comment by rsolomakhin** [comment]
Will merge after travis-ci completes.

**Comment by tanderson-google** [comment]
Googletest on the bots doesn't support INSTANTIATE_TEST_SUITE_P

**Comment by rsolomakhin** [comment]
We can either checkout the new googletest from github (we do this for re2) in `.travis.yml` or land your libcpp change individually. Up to you.

**Comment by tanderson-google** [comment]
Please feel free to land the libc++ change, thanks!

**Pull request closed without merging**
