### PR TITLE
Update MD5 implementation from current Chromium source code

### PR DESCRIPTION
**Pull request by roubert**
This modernizes the code style, most notably removing the nowadays deprecated register storage class specifier.

I noticed that Travis CI warned about the use of deprecated code. If you have any other integration tests to run, please run them before merging this pull request, I've only tested it using Travis CI.

### CODE REVIEW

**Comment by rsolomakhin** [comment]
LGTM

**Comment by madmath** [comment]
Isn't the development process to submit changes internally and then do an open-source dump?

**Comment by roubert** [comment]
I have no idea what the process might be today. Originally, this project was developed fully public in a source code repository then hosted on Google Code.

**Comment by ssundarraj** [comment]
Closing this in favor of pulling changes from internal repo.

**Pull request closed without merging**
